schema_version = "1.0.0"
id = "Shapekeytool"
name = "Shapekeytool"
version = "0.1.1"
tagline = "shapkey toolkit."
maintainer = "Community"
type = "add-on"
tags = ["Mesh"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
# website = "https://projects.blender.org/extensions/***"
# copyright = ["2024 Bart Crouch", "2024 Vladimir Spivak (cwolf3d)"]
